name: melodia-content-api

services:
  content-api:
    image: content-api:latest
    container_name: content-api
    restart: unless-stopped
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
      DATABASE_URL: "${DATABASE_URL}"
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "8080:8080"
    networks:
      - melodia-network

networks:
  melodia-network:
    driver: bridge