name: melodia-content-api

services:
  content-api:
    image: content-api:latest
    container_name: content-api
    restart: unless-stopped
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
      MONGO_URL: "${DATABASE_URL}"
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - melodia-network

networks:
  melodia-network:
    driver: bridge