name: melodia-content-api

services:
  content-api:
    image: content-api:latest
    container_name: content-api
    restart: unless-stopped
    environment:
      HOST: "0.0.0.0"
      PORT: "8080"
      DATABASE_URL: "${DATABASE_URL}"
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SUPABASE_BUCKET: ${SUPABASE_BUCKET}
      SUPABASE_URL: ${SUPABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      USER_API_BASE: ${USER_API_BASE}
    ports:
      - "8080:8080"
    networks:
      - melodia-network

networks:
  melodia-network:
    driver: bridge